### ISSUE TITLE
Token doesn't take tokens (dead or alive) into account

### ISSUE THREAD

**Issue by iFatewing** [ironmonk108/enhanced-terrain-layer#102]
Together with Drag Ruler and Terrain Ruler, the Enhanced Terrain Layer module does work with difficult terrain tiles, but (even when checked) doesn't take into account when walking over dead or alive tokens/creatures

**To Reproduce**
Tested in an old world and in a new one!
1. Activate the Modules "Drag Ruler (Traumi's Patch)" and "socketlib", "Enhanced Terrain Layer" and "Terrain Ruler"
2. In Settings, check "Include Live Tokens" and "Include Dead Tokens"
3. Try to drag a Token over a friendly/enemy token or over a dead one.
4. Both types do not count as difficult terrain!

**Expected behavior**
Dead or Alive Tokens should count as difficult terrain, when being dragged over!

**Screenshots**
![enhanced terain layer problem #1](https://user-images.githubusercontent.com/114588683/192787791-1b8504d4-05b1-40b0-8a6b-fa2abcab27a2.PNG)
![enhanced terain layer problem #2](https://user-images.githubusercontent.com/114588683/192787820-45bc9a74-cc0d-4788-93a5-7948f294b55a.PNG)
![enhanced terain layer problem #3](https://user-images.githubusercontent.com/114588683/192788294-bf74e801-3cbb-442d-9e41-8b75c22fed9a.PNG)
![enhanced terain layer problem #4](https://user-images.githubusercontent.com/114588683/192788404-895059d2-b3b4-4d31-9584-474316efc385.PNG)

**Please complete as much of the following information as possible:**
 - Foundry Version 10, Build 286
 - System D&D5e
 - Module version 10.3
 - No errors in the console

**Additional context**

**Comment by Ironxxx** [comment]
This is the same for PF2e

**Comment by ironmonk88** [comment]
I believe this is fixed with the latest version.  If it is not, please re-open this ticket.
