### ISSUE TITLE
[BUG] Measurement templates will cause listAllTerrain to fail

### ISSUE THREAD

**Issue by manuelVo** [ironmonk108/enhanced-terrain-layer#103]
**Describe the bug**
When measurement templates are placed on a scene, `listAllTerrain` fails with the following stack trace
![stack trace](https://user-images.githubusercontent.com/1705157/193270920-d678d37f-aca6-414a-a5b8-e4860b0e9e94.png)

**To Reproduce**
1. Place a circular measurement template on the scene
2. Execute `canvas.terrain.listAllTerrain()`

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
