### ISSUE TITLE
[BUG] Double-Click to create hex terrain

### ISSUE THREAD

**Issue by Crowguard** [ironmonk108/enhanced-terrain-layer#106]
Terrain created this way is a bit off from the actual grid. Both vertical & horizontal hexes.

https://user-images.githubusercontent.com/99844555/194969914-7f4742f1-c9d2-4f6a-a1b2-94886210c617.mp4

Foundry 10.288
ETL 10.4
FTC ✔️

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
