### ISSUE TITLE
[BUG] Randomly using double movement on non-difficult terrain

### ISSUE THREAD

**Issue by iFatewing** [ironmonk108/enhanced-terrain-layer#108]
**Describe the bug**
While Drag Ruler (Traumi's Patch) [1.12.13], Enhanced Terrain Layer [10.4] and Terrain Ruler [1.7.1] active tokens randomly need twice the movement for non-difficult terrain squares.

**To Reproduce**
1. Go to Configurations and to Enhanced Terrain Layer.
2. Check "Include Live Tokens" and "Include Dead Tokens" to Any.
3. Test dragging a token over the canvas. It counts difficult terrain but randomly also uses double movement on non-difficult terrain...

**Expected behavior**
Dragging over the canvas should only count as difficult terrain, when moving over difficult terrain, dead or live tokens.

**Screenshots**
![Error Console Drag Ruler + Enhanced Terrain Layer](https://user-images.githubusercontent.com/114588683/194995346-360b525b-e07a-4db5-a2de-86f83e3bd79d.PNG)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 10 (Build 288)
 - System D&D 5e (2.0.3)
 - Drag Ruler (Traumi's Patch) [1.12.13], Enhanced Terrain Layer [10.4] and Terrain Ruler [1.7.1]
 - see the errors in console in the screenshot. Unfortunately, i couldn't make a screenshot of the bug itself.
 - Error only occurs when "Include Live Tokens" and "Include Dead Token" are active. Tested both in new and existing worlds...

**Comment by ironmonk88** [comment]
I believe this is fixed with the latest version.  If it is not, please re-open this ticket.
