### ISSUE TITLE
[BUG] Terrain caused by measurement tempates is being ignored

### ISSUE THREAD

**Issue by manuelVo** [ironmonk108/enhanced-terrain-layer#112]
The function `listTemplateTerrain()` always returns an empty array.

I suspect this happens because of this line: https://github.com/ironmonk88/enhanced-terrain-layer/blob/2313376a5b4bd8f6b71f3b8ea2d6b831072e65dd/classes/terrainlayer.js#L204

Shouldn't it be requesting the property `document.flags.enhanced-terrain-layer` instead of `flags.enhanced-terrain-layer`?

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
