### ISSUE TITLE
[BUG] canvas.terrain.terrainFromGrid fails with an error if no option is specified

### ISSUE THREAD

**Issue by manuelVo** [ironmonk108/enhanced-terrain-layer#114]
When invoking `canvas.terrain.terrainFromGrid` without explicitly setting an option object, the function fails with an error:

![grafik](https://user-images.githubusercontent.com/1705157/195998425-e7f50e96-acbb-4b70-8ab3-1beb1e3aa7c0.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
