### ISSUE TITLE
[BUG] Error when using canvas.terrain.get("someid")

### ISSUE THREAD

**Issue by KayelGee** [ironmonk108/enhanced-terrain-layer#116]
**Describe the bug**
When trying to find a terrain object via id by calling `canvas.terrain.get('id of object')` an error will be thrown: 
```
Uncaught Error: Terrain is not a valid embedded Document within the Scene Document
    at Scene.getEmbeddedCollection (commons.js:6268:15)
    at get documentCollection [as documentCollection] (foundry.js:30567:26)
    at TerrainLayer.get (foundry.js:30778:17)
```
**To Reproduce**
1. type the following into the console(id doesn't matter as it throws before actually checking the id): `canvas.terrain.get('id of object')` 

**Expected behavior**
Return the object that fits the id.

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari]: any
 - Foundry Version [e.g. v9]: v10
 - System [e.g. D&D5e, Pathfinder 2e]: any
 - Module version: 10.5
 - Are there any errors in the console [e.g. press F12 and look for red text]: yes see the text above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.: yes

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by KayelGee** [comment]
Thanks for that. This was preventing me from adding support to token attacher
