### ISSUE TITLE
[BUG] Creating rough  terrain and labeling it as water isn't allowing players with a swim speed to act as if it was regular terrain

### ISSUE THREAD

**Issue by justjoekingg** [ironmonk108/enhanced-terrain-layer#118]
Creating a zone of rough terrain and labeling the environment as Water doesn't allow players in my 2nd edition Pathfinder game with a swim speed to measure the terrain as regular movement.
Am I missing anything or am I using something wrong?
I have the modules drag ruler and terrain ruler installed. The only way tokens are treating it as regular terrain is if I elevate their token to be above it.

![image](https://user-images.githubusercontent.com/97271884/198856007-49563652-8930-4ce2-b997-0194d3cb8afd.png)

**Comment by vizorian** [comment]
I believe you need the [DnD5e Drag Ruler Integration](https://foundryvtt.com/packages/elevation-drag-ruler) module as well for this to work.
I do have the same issue, and the creator of the Integration DnD5e Drag Ruler Integration module says it's due to a bug with this module.

**Comment by PepijnMC** [comment]
The PF2e system or integration module for that system is in charge of implementing this type of behavior. This is not something Enhanced Terrain Ruler does itself.

**Comment by velara** [comment]
The feature was removed from PF2e Drag Ruler Integration during the transition to v10. It will hopefully be returning soon-ish.

**Comment by velara** [comment]
Should be working now.

**Comment by ironmonk88** [comment]
Closing this as it's something the ruler does, not Enhanced Terrain Layer.
