### ISSUE TITLE
[BUG] terrainFromPixels() broken as of 10.4

### ISSUE THREAD

**Issue by DrMcCoy** [ironmonk108/enhanced-terrain-layer#119]
60286580cdb384a30b426475396e4afe34ff11b1 broke the function terrainFromPixels() by introducing this line: https://github.com/ironmonk88/enhanced-terrain-layer/commit/60286580cdb384a30b426475396e4afe34ff11b1#diff-e4b9aa86b3c16659cb4cf6ab84529434c758ef722a37e94097be3eeffcf465e0R319

Namely, it throws a ReferenceError: options is not defined.

This is used via terrainFromGrid() in the Speed Provider implementation for Drag Ruler in the Pathfinder 1e system.

**Comment by DrMcCoy** [comment]
I temporarily fixed it with this

```
diff -ur modules/enhanced-terrain-layer.orig/classes/terrainlayer.js modules/enhanced-terrain-layer/classes/terrainlayer.js
--- modules/enhanced-terrain-layer.orig/classes/terrainlayer.js	2022-10-31 21:56:09.554626417 +0100
+++ modules/enhanced-terrain-layer/classes/terrainlayer.js	2022-10-31 21:57:33.350299167 +0100
@@ -316,12 +316,12 @@
         return this.costWithTerrain(pts, terrain, options);
     }
 
-    terrainFromGrid(x, y) {
+    terrainFromGrid(x, y, options = {}) {
         let [gx, gy] = canvas.grid.grid.getPixelsFromGridPosition(y, x);
-        return this.terrainFromPixels(gx, gy);
+        return this.terrainFromPixels(gx, gy, options);
     }
 
-    terrainFromPixels(x, y) {
+    terrainFromPixels(x, y, options = {}) {
         const hx = (x + (canvas.dimensions.size / 2));
         const hy = (y + (canvas.dimensions.size / 2));
 
```

The error is gone, but I'm not sure if that's the intended use.

**Comment by PepijnMC** [comment]
See https://github.com/ironmonk88/enhanced-terrain-layer/issues/111

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
