### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk108/enhanced-terrain-layer#121]
**Describe the bug**
the rule does not consider the elevation of tokens

**To Reproduce**
1. create 2 tokens on map and set one with elevation 30
2. set live tokens are difficult terren
3. drag the token on 30 above the token with 0;
4. and token with 0 are tedifficult terrein for them.

**Expected behavior**
the token below (more then 5) from another could not cause difficult terrain, only those with the same elevation

**Screenshots**
Not necessery

**Please complete as much of the following information as possible:**
 - Browser Brave
 - Foundry Version v10.291
 - System  D&D5e, 
 - Module version 10.6

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
