### ISSUE TITLE
[Feature Request] Add "Force Snap To Point" option for polygon drawing

### ISSUE THREAD

**Issue by LostCarcosa** [ironmonk108/enhanced-terrain-layer#129]
**Is your feature request related to a problem? Please describe.**
The default snap-to-subgrid settings make quickly outlining grids slower and difficult, especially on hex maps, as greater care has to be taken to place each vertex at a grid intersection and not slightly off. 

This is mostly relevant for hex grids, where trying to border an area with enhanced terrain involves quite a lot of placement.

**Describe the solution you'd like**
Implement a "Force Snap To Point" option for the enhanced terrain polygon drawing tool, which would cause it to snap to the nearest grid intersection. Foundry has this option in core for walls, and the Advanced Drawing Tool module has an implementation for Drawings.

**Comment by Kikumono** [comment]
+1 upvote

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
