### ISSUE TITLE
[BUG] Terrain Doesn't Save

### ISSUE THREAD

**Issue by Crowguard** [ironmonk108/enhanced-terrain-layer#132]
1. Draw terrain.
2. Switch to a different scene, then switch back.
3. Terrain is gone.

https://user-images.githubusercontent.com/99844555/232272613-2d252d11-bb70-4270-822d-235014285c2a.mp4

ETL 10.7
FTC Brand new world.

**Comment by Crowguard** [comment]
Just booted up my various worlds and the terrain I drew is there now? 

![image](https://user-images.githubusercontent.com/99844555/232336447-2a53c061-bc32-4646-8029-464246df6246.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
