### ISSUE TITLE
[BUG] Canvas Drawing Failed on New Scene

### ISSUE THREAD

**Issue by ashmedai711** [ironmonk108/enhanced-terrain-layer#133]
**Describe the bug**
After updating to ETL 10.8 or 10.7, when viewing a newly created scene, there is an error that reads "Canvas drawing failed: Cannot read properties of null (reading 'map')"

**To Reproduce**
1. Be on ETL 10.8 or 10.7
2. Create a new scene
3. View the newly created scene
4. Receive error "Canvas drawing failed: Cannot read properties of null (reading 'map')"

**Expected behavior**
Newly created scene should not throw an error

**Screenshots**
<img width="673" alt="image" src="https://user-images.githubusercontent.com/119912908/232634902-41477f2c-35fa-47bc-9dfd-fc8036fe042d.png">

**Please complete as much of the following information as possible:**
 - Browser: Chrome v 112.0.5615.50
 - Foundry Version 10.291
 - SystemD&D5e 2.1.5
 - Module version 10.8
 - Are there any errors in the console [e.g. press F12 and look for red text]: Yes, see screenshot
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.: No, recreated the issue in a blank world with no other modules instead.

**Additional context**
No issue on ETL 10.6 or below and existing scenes also appear to be fine.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
