### ISSUE TITLE
[BUG] Error on scene without background map

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk108/enhanced-terrain-layer#135]
Got this error creating a scene without a background map.
<img width="589" alt="Screen Shot 2023-04-29 at 5 14 39 PM" src="https://user-images.githubusercontent.com/90105219/235328470-48fad443-c8fb-427a-89cd-d5f167b9f347.png">

**Comment by ironmonk88** [comment]
Duplicate of #133
