### ISSUE TITLE
TypeError: Canvas drawing failed: documents is null. documents is null

### ISSUE THREAD

**Issue by ckdragons** [ironmonk108/enhanced-terrain-layer#136]
![image](https://github.com/ironmonk88/enhanced-terrain-layer/assets/84493092/d9e9c922-6aa7-4366-9fa4-5cf8b119c6fb)

Running Foundry 10.291 with Pathfinder 1e 0.82.5

**Comment by maddoodles** [comment]
Just wanted to chime in to say I've also had this issue, rolling back to 10.6 fixed it for me.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
