### ISSUE TITLE
[BUG] Tokens Only Working on Exact Elevation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk108/enhanced-terrain-layer#139]
Tokens are only having movement adjusted when they're at the elevation; not while they're in range of the depth.

All terrain here is the same; the 59 elevation token should be encountering the difficult terrain.

https://github.com/ironmonk88/enhanced-terrain-layer/assets/99844555/5ee60d42-396c-42e4-bcb1-4e9f96ef5b03

ETL 10.09

![image](https://github.com/ironmonk88/enhanced-terrain-layer/assets/99844555/cb42b0ed-e50e-4167-898f-575082c2e488)

**Comment by ironmonk88** [comment]
Working exactly as expected.
The elevation is 60, which is the base, and the depth is positive... so you're covering 60 and 61.
If you want to cover 59, then set the elevation to 60 and the depth to -1.
