### ISSUE TITLE
Terrain layer unresponsive

### ISSUE THREAD

**Issue by Swipswap22** [ironmonk108/enhanced-terrain-layer#141]
When I try to create new terrain, the "Draw" tools do not work at all for me; nothing is shown on screen, on my cursor, or after any alt/shirt/ctrl pressing or holding. The "select", "toggle terrain always displayed", and "reset terrain" tools seems to work fine, but I am unsure without terrain to actively test it on. All other base Foundry tools, like the drawing tools which function similarly, work just fine. 

I have read the "Usage and Current Features" section on Github and I am using the correct inputs. I have tried reloading the page, disabling and reenabling the module, reinstalling the module, restarting the world, and restarting my computer.

I am new to Foundry and a Github noob so I wouldn't be surprised if this error is on my end, but I don't know what is causing this or how I can fix it, or if this is even the right place to ask for help. Please redirect me to the right place if this is not the appropriate place to ask, and let me know if you need any further information from my system or game to help me figure this out.

**Here are my support details:**
Foundry Virtual Tabletop: Version 11 Stable, 11.299
Game System: dnd5e, 2.2.1
Active Modules: 15
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 19456 x 19456 | Grid Size: 256 | Padding Percentage: 0.25
Walls: 723 | Ambient Lights: 80 | Ambient Sounds: 5 | Tiles: 6 | Tokens: 0

Actors: 5 | Items: 870 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 4 | Compendium Packs: 22 | Chat Messages: 217

**These are by active modules**
![image](https://github.com/ironmonk88/enhanced-terrain-layer/assets/51305550/88b5ccf1-cce5-466c-92ac-b265d4d12a70)

**Comment by Thorarin** [comment]
There are several deprecated calls involved when attempting to draw any shapes on the terrain layer.
They appear to be caught by some accessors intended for backward compatibility, but I don't think they're 100% compatible.

When I try to draw a square area, I get to deprecation warnings, followed by an uncaught exception:

> commons.js:2004 Error: event.data.origin is deprecated in favor of event.interactionData.origin.
> Deprecated since Version 11
> Backwards-compatible support will be removed in Version 12
>     at Object.logCompatibilityWarning (commons.js:1993:19)
>     at Xt.get (foundry.js:31665:25)
>     at TerrainLayer._onDragLeftStart (terrainlayer.js:509:57)
> logCompatibilityWarning @ commons.js:2004
> get @ foundry.js:31665
> _onDragLeftStart @ terrainlayer.js:509
> await in _onDragLeftStart (async)
> _onDragLeftStart @ foundry.js:26945
> onDragLeftStart @ main.js:72
> wrapper @ libwrapper_shim.js:57
> callback @ foundry.js:31126
> #handleDragStart @ foundry.js:31453
> #handleMouseMove @ foundry.js:31435
> notifyListeners @ earcut.js:128
> notifyTarget @ earcut.js:128
> propagate @ earcut.js:128
> dispatchEvent @ earcut.js:128
> mapPointerMove @ earcut.js:128
> mapEvent @ earcut.js:128
> onPointerMove @ earcut.js:128

> commons.js:2004 Error: TerrainDocument defines TerrainDocument.prototype._validateModel instance method which should now be declared as TerrainDocument.validateJoint static method.
> Backwards-compatible support will be removed in Version 13
>     at Object.logCompatibilityWarning (commons.js:1993:19)
>     at TerrainDocument.validateJoint (commons.js:7120:23)
>     at TerrainDocument.validate (commons.js:7071:28)
>     at new DataModel (commons.js:6816:12)
>     at new Document (commons.js:7479:3)
>     at new BaseTerrain (terraindocument.js:29:8)
>     at new ClientDocumentMixin (foundry.js:13893:7)
>     at new CanvasDocument (foundry.js:13247:10)
>     at new TerrainDocument (terraindocument.js:104:8)
>     at TerrainLayer._onDragLeftStart (terrainlayer.js:511:26)
> logCompatibilityWarning @ commons.js:2004
> validateJoint @ commons.js:7120
> validate @ commons.js:7071
> DataModel @ commons.js:6816
> Document @ commons.js:7479
> BaseTerrain @ terraindocument.js:29
> ClientDocumentMixin @ foundry.js:13893
> CanvasDocument @ foundry.js:13247
> TerrainDocument @ terraindocument.js:104
> _onDragLeftStart @ terrainlayer.js:511
> await in _onDragLeftStart (async)
> _onDragLeftStart @ foundry.js:26945
> onDragLeftStart @ main.js:72
> wrapper @ libwrapper_shim.js:57
> callback @ foundry.js:31126
> #handleDragStart @ foundry.js:31453
> #handleMouseMove @ foundry.js:31435
> notifyListeners @ earcut.js:128
> notifyTarget @ earcut.js:128
> propagate @ earcut.js:128
> dispatchEvent @ earcut.js:128
> mapPointerMove @ earcut.js:128
> mapEvent @ earcut.js:128
> onPointerMove @ earcut.js:128

> terrain.js:195 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'texture')
>     at Terrain._draw (terrain.js:195:59)
>     at Terrain.draw (foundry.js:27912:16)
>     at TerrainLayer._onDragLeftStart (terrainlayer.js:514:24)
>

**Comment by terrysidhu** [comment]
Gotta love the Ironmonk!  Just starting to get my Foundry on, started with v11 -- have a feeling I should  have started with v.10 but most things work.  Thought this might be a nice addition after watching Baileywiki and Ironmonk... I just tend to install whatever he makes cause they're all awesome.  But this is definitely not working for me on v.11  -- as OP said, no drawing happening at all.

![image](https://github.com/ironmonk88/enhanced-terrain-layer/assets/43838083/49676a61-4a65-435a-b371-ed8433761bb7)

**Comment by AlastarOG** [comment]
Same thing here, can't draw anything.

**Comment by Swipswap22** [comment]
Unfortunately I think Ironmonk is aware of the issue and unable to solve it, his most recent update on the main page suggests that V11 has been a pain and that support for the module will cease until potentially V12 provides the necessary resources to continue. Unfortunate, I just started using Foundry and this seemed like an excellent module, but I understand the difficulty and hope there's a turn for the better in the future.
