### ISSUE TITLE
Request: add Earth/Stone as default terrain type

### ISSUE THREAD

**Issue by Merudo** [ironmonk108/enhanced-terrain-layer#18]
In D&D 5e, the Earth Genasi has the following feature:

```
Earth Walk: You can move across difficult terrain made of earth or stone without expending extra movement.
```

I wonder what's the best approach to implement this in Enhanced Terrain Layer? Maybe an extra default environment or obstacle type for "Rock/Stone" would work well?

There already is a "mountain" environment but rocks on the ground, caves, etc. are not really mountains.

**Comment by ironmonk88** [comment]
I would just use Rubble for that.  Rubble is essentially rocks on the ground.
I'd thought about having a default environment, but there's just too many systems and worlds out there that have their own way of doing things to be able to have a decent "default".  Leaving it as a generic difficult terrain is probably best, with the option for the GMs to get more specific.
