### ISSUE TITLE
Allow terrain layer drawings to "snap-to-grid"

### ISSUE THREAD

**Issue by Merudo** [ironmonk108/enhanced-terrain-layer#19]
When adding walls, regular drawings, or other elements, Foundry can have the element "snap to grid", meaning the element will snap to the corner of a square.

It would be great if a similar snap-to-grid feature would be implemented with Enhanced-Terrain-Layer, to easily create rectangular squares of difficult terrain.

**Comment by ironmonk88** [comment]
Ummm... it already snaps to grid.
It's on the same 1/4 system that Tiles use.
And if you hold down Shift while drawing it will let you free form it instead of snapping to the grid.
