### ISSUE TITLE
Gridless functionality

### ISSUE THREAD

**Issue by VexxMyst** [ironmonk108/enhanced-terrain-layer#20]
So I just started messing with this module and love it; but I've run into a rather significant problem (for me).

So while a square grid works perfectly fine and counts difficult terrain properly...
![Screenshot (397)](https://user-images.githubusercontent.com/74265604/117208516-37b88680-adc3-11eb-92b0-e88d6a93df58.png)

...A gridless map does not.
![Screenshot (398)](https://user-images.githubusercontent.com/74265604/117208644-5fa7ea00-adc3-11eb-9178-6b0381e56edb.png)

This is a major problem for me because I'm working on a game that would be played gridless. The polygon aspect of the module lends itself really well to this, so I hope this is something that can be amended.

**Comment by VexxMyst** [comment]
Okay, seeing as the Measure With Difficult Terrain tab deactivates when I disable Terrain Ruler, it looks more like I need to bring this issue to them instead. My apologies.

**Comment by ironmonk88** [comment]
Yeah, this is definitely with the Ruler.  I know they were working on having it available with gridless terrain, but it definitely poses a much more complicated solution than when you have a grid.  Not sure how far along they got with it.

Closing the ticket.
