### ISSUE TITLE
Import ability-template.js using relative path

### ISSUE THREAD

**Issue by Tyaeth** [ironmonk108/enhanced-terrain-layer#21]
I recently moved my server behind a nginx reverse proxy and started seeing the following error in the console:

`Failed to load resource: the server responded with a status of 404 (Not Found)    terrain-main.js:232 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module `

Upon inspection, and a bit of snooping around on the Foundry discord, a user named Fez encountered the same issue with another module, and it turned out that the module they were having issues with wasn't referencing the D&D5e system files using a relative path. 

Changing 
`const importedJS = await import("/systems/dnd5e/module/pixi/ability-template.js");` 
to
`const importedJS = await import("../../systems/dnd5e/module/pixi/ability-template.js");`
seems to solve the problem for me.

**Comment by ironmonk88** [comment]
Thank you for that.
I ended up rewriting this code for a different issue.  Using libWrapper to do the work of handling the ability template changes.
Good to know though in case this comes up again.
