### ISSUE TITLE
Update the readme with types of terrain?

### ISSUE THREAD

**Issue by dmrickey** [ironmonk108/enhanced-terrain-layer#25]
I've seen people say that this mod does more than "difficult terrain" and that you can also assign water areas. The readme only mentions "difficult terrain". Are there other types of terrain?

**Comment by ironmonk88** [comment]
You can set the environment of the terrain.  Such as water.  Problem is... the environment can be set by the system, or by the world.  So I have a set of default ones, but they can easily be changed to something else.

I've updated the readme to make mention that you can set the environment.  And added the other features and updates that have been added.
