### ISSUE TITLE
Request: single click terrain placement

### ISSUE THREAD

**Issue by Ironxxx** [ironmonk108/enhanced-terrain-layer#26]
this is a great mod (thanks for it, it really enhances tactical play) but the one thing the original Terrain Layer does better is the speed you can place difficult terrain. Drawing it out as a polygon can be a chore. It would be great to get single click placement where one square is converted into some default x2 difficult terrain as an additional tool.

**Comment by ironmonk88** [comment]
Double-clicking on a the canvas with the Add Difficult Terrain button selected will now drop a default terrain.
It's subject to the default type (can be configured in the scene) and cost (can be configured to the right of the terrain controls).
