### ISSUE TITLE
Option to not show diabled Terrain on the GMs view if the Terrain Layer isn't active

### ISSUE THREAD

**Issue by manuelVo** [ironmonk108/enhanced-terrain-layer#28]
I'd love to see an option that makes it so that disabled terrain isn't shown for the GM when the Terrain Layer tool isn't active. That would allow me to more easily use the battlemap without "future" terrain getting in my way while it isn't relevant yet.

**Comment by ironmonk88** [comment]
Will be in the next release.

**Comment by ironmonk88** [comment]
Option has been added to the latest release.
