### ISSUE TITLE
Terrain dissappears if it's being dropped on itself

### ISSUE THREAD

**Issue by manuelVo** [ironmonk108/enhanced-terrain-layer#29]
When a terrain is being dragged and then dropped at the position at which it's already at, the terrain will disappear until it's being deselected with a mouse click.

https://user-images.githubusercontent.com/1705157/119090820-61e98580-ba0c-11eb-8665-ca7761a2df22.mp4

**Comment by ironmonk88** [comment]
That was really weird.
Should be fixed with the latest version.

Also thanks for the video, that was really helpful to see what was happening.
