### ISSUE TITLE
Overlapping regions do not behave as expected

### ISSUE THREAD

**Issue by revilowaldow** [ironmonk108/enhanced-terrain-layer#31]
Values do not behave as expected when regions are overlapped. In this case an x0.5 region is placed over an x2 region and only the x2 region is considered. 
(In the event this is caused by one of the other modules and not here, please let me know and I'll slide the issue down the chain.)

A test case is shown below using the modules Drag Ruler and Terrain Ruler:
![image](https://user-images.githubusercontent.com/52298102/119403569-795b9380-bcd6-11eb-9c86-2316a6cd8044.png)
Test Environment:
![image](https://user-images.githubusercontent.com/52298102/119403656-9a23e900-bcd6-11eb-934d-c487a7266403.png)

A real world use case:
![image](https://user-images.githubusercontent.com/52298102/119403715-ac9e2280-bcd6-11eb-9f1d-3390f32cfd63.png)

**Comment by ironmonk88** [comment]
I spent some time thinking about this... but what it comes down to is that the module doesn't exactly know what you mean by this.  Essentially, which one cancels out the other.  You could have easy terrain that is negated by the difficult terrain, ie it was easy until some effect made it difficult.  Alternatively you could have difficult terrain made easier.

DnD5e rules means difficult terrain doesn't stack, it takes the most difficult one and uses that.  So in the above example, the terrain is calculating correctly.

In your example above, to make it clear for the module what you're intending, you'd probably need the draw the outer difficult terrain as a donut, or large C with the edges together.  That would eliminate the overlap and make it clear to the module which terrain to use.  If you drew the split along one of the diagonal lines it would show nearly seamless

![image](https://user-images.githubusercontent.com/75920956/121797159-5d5f5980-cbd3-11eb-9856-223d115711c0.png)
