### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by Nedrapter** [ironmonk108/enhanced-terrain-layer#33]
I have Enchanced Terrain Layer and Drag Ruler modules enabled. I'm setting up a terrain and nothing changes when trying to move a token over it. No errors reported on console. Foundry version is 0.7.10 (as I have many incompatibilities to upgrade to 0.8.6 atm)
![image](https://user-images.githubusercontent.com/74311190/121021548-2c81bd80-c7aa-11eb-853c-e589e439d6e0.png)

**Comment by ironmonk88** [comment]
You also need Terrain Ruler.  The three work together.
Enhanced Terrain Layer records difficult terrain, but doesn't inherently do anything with it.
Drag Ruler shows the fancy colouring.
Terrain Ruler is the one that communicates between the ruler and the terrain layer, and does the calculations.  The ruler was split on two just in case people wanted one but not the other.

**Comment by Nedrapter** [comment]
Thanks, that makes sense , was getting crazy there :P
