### ISSUE TITLE
Tokens count as difficult terrain

### ISSUE THREAD

**Issue by Avitale34** [ironmonk108/enhanced-terrain-layer#34]
I remember there being a feature to make tokens count as difficult terrain, is that still a feature?

**Comment by ironmonk88** [comment]
That is still a feature.  It won't work on gridless, but does work on both hex and square.
Bearing in mind that you'll need to be using a ruler that supports that.
Terrain Ruler is my recommendation, with Drag Ruler to add some cool colours.

**Comment by ironmonk88** [comment]
It is a setting that you can turn off (or on) in Enhanced Terrain Layer.
And as far as I know it's still working.
What issue are you having?

**Comment by Avitale34** [comment]
I uninstalled enhanced terrain layer and reinstalled and that fixed the issue :)

**Comment by ironmonk88** [comment]
Yayyy.  Glad it's working now.  Closing the ticket.
