### ISSUE TITLE
I can't make the cost count

### ISSUE THREAD

**Issue by brunocalado** [ironmonk108/enhanced-terrain-layer#36]
Hi.

I can't make the cost be accounted. Can you help me?

fvtt 8.6 + google chrome + swade 19.4
drag ruler + enhanced-terrain-layer

https://user-images.githubusercontent.com/4999783/121898435-bfb27a00-ccf9-11eb-86b9-1f77e2db6a2a.mp4

**Comment by Luisphigor** [comment]
You need to install "Terrain Ruler" module, it makes Foundry's rulers respect difficult terrain that was put down using the Enhanced Terrain Layer module.

**Comment by ironmonk88** [comment]
Luisphigor is correct.  Enhanced Terrain Layer just stores information.  Terrain Ruler is what allows a ruler to use the information.  Drag Rule is just an amazing ruler.
