### ISSUE TITLE
terrainAt returning an empty array

### ISSUE THREAD

**Issue by caewok** [ironmonk108/enhanced-terrain-layer#38]
**Setup**
Foundry 0.8.6
dnd5e 1.3.3
Enhanced Terrain Layer 1.0.29

**Issue**
`canvas.terrain.terrainAt(x, y)` seems to only return a blank array for a simple test. In a new map (basic square grid), I created a new terrain using the terrain layer functions. Then I put an actor within the terrain polygon and tried to do the following in the console:

```js
let token = canvas.tokens.controlled[0];
canvas.terrain.terrainAt(token.data.x, token.data.y); // returns []; expected the terrain object or array with terrain object
```
I would have expected this to return the terrain object represented by the underlying terrain polygon. Is this a bug or am I doing it wrong?

**Edit**
The same problem occurs when using `canvas.terrain.cost(token)` or `canvas.terrain.cost(token, {verbose:true})`. Appears unable to find the underlying polygon for the token position.

**Additional info**
The polygon object appears to exist in the terrain object. For example:
`canvas.terrain.placeables`
> Array [ {…} ]
> 0: Object { _eventsCount: 2, alpha: 1, visible: true, … }
> length: 1
> <prototype>: Array []

**Comment by caewok** [comment]
I have been experimenting with this some more, and I think the problem is that something must have changed in how the placeable positions are being designated. The original `terrainAt` function converts the x,y position to pixels, but that no longer seems correct.

Original version:
```js
terrainAt(x, y) {
        const hx = canvas.grid.w / 2;
        const hy = canvas.grid.h / 2;
        let [gx, gy] = canvas.grid.grid.getPixelsFromGridPosition(y, x); // this appears to be the problem
        let terrains = this.placeables.filter(t => {
            const testX = (gx + hx) - t.data.x;
            const testY = (gy + hy) - t.data.y;
            return t.shape.contains(testX, testY);
        });

        return terrains;
    }
```

Proposed corrected version:
```js
terrainAt(x, y) {
        const hx = canvas.grid.w / 2;
        const hy = canvas.grid.h / 2;
        const shifted_x = x + hx;  // maybe slightly faster to move outside the filter loop
        const shifted_y = y + hy;  

        let terrains = this.placeables.filter(t => {
            const testX = shifted_x - t.data.x;
            const testY = shifted_y - t.data.y;
            return t.shape.contains(testX, testY);
        });

        return terrains;
    }
```

**Comment by ironmonk88** [comment]
I think the issue is, that terrainAt works off the grid coordinates, not the pixel coordinates.
I agree it's not very clear though.
I've split the function into two new functions terrainFromPixel and terrainFromGrid to make it easier to figure out which one to use.

**Comment by caewok** [comment]
Thanks!
