### ISSUE TITLE
canvas.terrain.cost() only returns empty arrays

### ISSUE THREAD

**Issue by yorkshirelandscape** [ironmonk108/enhanced-terrain-layer#43]
I've tried to get canvas.terrain.cost() working, but it never finds the difficult terrain I've placed, so it always returns 1. I've tried both pixel and grid coordinates and made absolutely sure I was using the right location.

IronMonk and I discussed this briefly on Discord and he acknowledged it was broken, but I figured it might help others to have this report here.

Currently using 0.8.8 with Pathfinder 2.4.0.6221 and ETL 1.0.31 on Windows 10 and Chrome.

**Comment by ironmonk88** [comment]
I went back to check it out... and it looks like it's working fine.
cost works off grid and not pixel co-ordinates.
if you use {ignoreGrid:true} as the options, then you can use pixel co-ordinates.

**Comment by yorkshirelandscape** [comment]
Right you are, sorry about that. I really did test it in grid mode, but I must have been wrong about what 1,1 was. Padding must still count or something.
