### ISSUE TITLE
Suggestion: ability to 'paint' terrain by selecting a square

### ISSUE THREAD

**Issue by Shandyan** [ironmonk108/enhanced-terrain-layer#44]
The old Terrain Layer module let you create difficult terrain by clicking on a grid square to mark it. I found this much easier to use than trying to create a polygonal area by drawing, and think it would be a useful feature to add in.

**Comment by ironmonk88** [comment]
Double-click on a square will let you do the same thing.

**Comment by Shandyan** [comment]
Oh, that does exactly what I want then! Thanks for the quick response.

**Comment by ironmonk88** [comment]
Not a problem.  :-)
