### ISSUE TITLE
Add Levels compatibility

### ISSUE THREAD

**Issue by Bobsson** [ironmonk108/enhanced-terrain-layer#45]
It would be great if this worked with the [Levels mod](https://github.com/theripper93/Levels) so that I could put difficult terrain on a floor without affecting the floors above and below it.

Example usage: Trapdoor opens into a room full of spikes.  The spikes are difficult to move through, but the floor above isn't.

**Comment by ironmonk88** [comment]
It should already support levels.  You can set the elevation of a Terrain Layer.  And using a ruler like Drag Ruler will calculate based on Token elevation.
The Levels mod might need to be updated to take into account elevation of the Terrain when determining what to show/hide.

**Comment by Bobsson** [comment]
After some further experimentation, I'm not quite sure what I was running into yesterday.  I can confirm that this works more-or-less as expected in conjunction with Levels.  (Min/max height means something very different than it does for that, but it's logical for this mod.)

That said, there is still one incompatibility, and I'm not sure which side the fix would be on.  Even though difficult terrain doesn't hinder movement when it's on a different level, the indicator area does still show up, regardless of the relative height of everything.  So an upper floor looks like difficult terrain, even if it doesn't act like it until the token goes down.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by Bobsson** [comment]
Thanks!
