### ISSUE TITLE
Allow different terrain blocks within same scene to have different environments

### ISSUE THREAD

**Issue by AJAnderson** [ironmonk108/enhanced-terrain-layer#49]
Currently environment is a scene level selection.

For things like region maps and world maps it would be great if environment types could be applied on a per-area basis. i.e. this area is mountains, this area is desert, that area is a wood, etc.

**Comment by ironmonk88** [comment]
The scene just set the default value, environment is set on a terrain by terrain basis.

![image](https://user-images.githubusercontent.com/75920956/128582865-32dfdde4-51df-40af-885a-001d67e28c26.png)

**Comment by AJAnderson** [comment]
Thank you, sorry I missed that!
