### ISSUE TITLE
Update difficulty modifier in HUD when using the Increase and Decrease Cost buttons.

### ISSUE THREAD

**Issue by RavenMage** [ironmonk108/enhanced-terrain-layer#50]
Foundry Version: 0.8.8
Enhanced Terrain Layer version: 1.0.32

When updating the cost of a difficult terrain polygon using the Increase and Decrease cost buttons on the HUD, the cost value displayed on the HUD doesn't update until the HUD is deactivated and then reactivated.
![enhanced_terrain_layer_hud_update](https://user-images.githubusercontent.com/5459117/128594365-0ce387b3-47e0-4c88-8efe-4d3f58e0e688.gif)

**Comment by ironmonk88** [comment]
The latest release should have this fixed.
