### ISSUE TITLE
Canvas won't load with an inactive terrain and the Perfect Vision module

### ISSUE THREAD

**Issue by RicoTheBold** [ironmonk108/enhanced-terrain-layer#55]
**Tested with a new world using:**
  Foundry VTT _0.8.9_
  Pathfinder 2nd Edition _2.13.2.7794 (system)_
  Perfect Vision _2.97_
  libWrapper _1.10.3.0 (required for Perfect Vision)_
  Enhanced Terrain Layer _1.0.32_

**Description of issue:**
  If a terrain drawing created with the Enhanced Terrain Layer module is set to "inactive" then the canvas drawing will fail, giving an error related to the terrain layer. The scene cannot be displayed until the Perfect Vision or Enhanced Terrain Layer modules are disabled.

**Steps to reproduce:**
  1. Load modules (default settings are fine)
  2. Create a new scene (default settings are fine)
  3. Select the Terrain Layer (triangle mountain icon), select the "Add Difficult Terrain" (pen icon) drawing tool for the terrain layer
  4. Draw a new polygon of terrain (same as drawing with default Foundry VTT drawing tool)
  5. Select the "Select Difficult Terrain" tool (box corners icon) and double-click to select the terrain you just created
  6. In the configuration window, check the "Inactive" box and click "Update Terrain"
  7. Switch to display a different scene and switch back to your scene (or you can probably just hit F5 to refresh, I guess) 
  8. Canvas will not display, and an error is logged.

**Other notes**
  Specifically it looks like a "drawing.drawDashedPolygon" function for drawing is getting nuked somewhere, and so the calls to that function bomb and it breaks the canvas.  When you set the terrain to hidden, it normally changes the border of the drawing to a dashed line, which is presumably handled by that function.

This didn't use to break, but I don't know exactly when it started. It took some hunting to figure out it was specifically the _inactive_ terrain that was the problem. On one map I had 2 created but inactive as pre-setup for a dynamic portion of a single map (out of 32 separate blocks of terrain). I ended up having to repeadtedly manually edit the exported scene JSON and import/test until I found the offending blocks of terrain. Sadly, disabling the drawing of borders in Enhanced Terrain Layer doesn't work - it would have been a nice workaround.

These are the errors displayed in the console.
![ETL and PV Error](https://user-images.githubusercontent.com/42160122/132104771-79f5cfb7-228f-4464-8865-3ce18f4fbc4e.PNG)

**Comment by RicoTheBold** [comment]
I have created a corresponding issue for the [Perfect Vision module](https://github.com/dev7355608/perfect-vision/issues/129)

**Comment by dev7355608** [comment]
PV replaces the default `Graphics` by `SmoothGraphics` and disables antialiasing (Foundry v9 is going to do this as well). I assume because of load order `PIXI.Graphics` is still `Graphics` when `drawDashedPolygon` is added to the prototype. But after PV loads `PIXI.Graphics`  is `SmoothGraphics`, and it cannot find `drawDashedPolygon` anymore.

```js
PIXI.LegacyGraphics = PIXI.Graphics;
PIXI.Graphics = PIXI.smooth.SmoothGraphics;
```

To fix this issue, I could add `drawDashedPolygon` to `SmoothGraphics` when I replace `PIXI.Graphics`, but it would be better if Enhanced Terrain Layer didn't modify `PIXI.Graphics` by adding `drawDashedPolygon`.

**Comment by ironmonk88** [comment]
I only have one function that uses it so it doesn't need to be all fancy and part of PIXI.Graphics.
It's been moved to a local function within the Terrain object.

**Comment by ironmonk88** [comment]
That took way too long to release.  But it's been changed in the latest version.
