### ISSUE TITLE
Feature Request: allow 'Dead cause difficult terrain' option to function without 'Tokens cause difficult terrain' option checked

### ISSUE THREAD

**Issue by sealtrowitz** [ironmonk108/enhanced-terrain-layer#56]
In some game system rulesets, "dead/defeated" characters cause difficult terrain. My feature request would be to allow the 'Dead cause difficult terrain' option of the module to function without the 'Tokens cause difficult terrain' option checked. As far as I understand, the two are currently tied to each other through the code, and dead tokens cannot cause difficult terrain without _all_ tokens causing difficult terrain. Separating these functions from each other would allow just tokens marked as "dead/defeated" to cause difficult terrain, while all other tokens would not.

**Comment by ironmonk88** [comment]
Should be added in the latest release.
