### ISSUE TITLE
Feature request: Permit a token to ignore (types of?) difficult terrain

### ISSUE THREAD

**Issue by Cr0w1ey** [ironmonk108/enhanced-terrain-layer#60]
For example, I'm rigging Cryovain for DoIP and have set the roof to be difficult (icy) terrain for the PC's, but Cryovain can ignore this difficult terrain type. I guess it might similarly be applied for a PC with Freedom of Movement?

**Comment by ironmonk88** [comment]
Enhanced Terrain Layer is just a library.  It doesn't really affect the tokens at all.
You'd need to find a Ruler that could do that.
I know there's a ruler for Pathfinder 2 that will allow a token to ignore difficult terrain.
So the capability exists to support a Ruler in doing that... but it's not something that Enhanced Terrain Layer itself does.

**Comment by Cr0w1ey** [comment]
Thanks so much for explaining that, and thanks for the module!
