### ISSUE TITLE
Feature request: Add opacity slider for terrain polygons

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [ironmonk108/enhanced-terrain-layer#61]
The effect of difficult terrain is pretty obvious to spot on the map. I propose to make the opacity adjustable to a GM can make it less "in your face" on maps that would create a strong contrast. For this purpose a global slider would be the way to adjust the opacity. Ideally there is also an override for each terrain polygon.

**Comment by ironmonk88** [comment]
Do you mean the Terrain Opacity slider?
![image](https://user-images.githubusercontent.com/75920956/140459524-3052925c-2958-4758-929a-9fa4270a7be7.png)
