### ISSUE TITLE
Compatibility with Show Drag Distance?

### ISSUE THREAD

**Issue by Verthiss** [ironmonk108/enhanced-terrain-layer#63]
Hi!
I would really like to use this module, but it breaks the Show Drag Distance Module:
https://github.com/wsaunders1014/ShowDragDistance

...a mod that I find to be amazingly convenient to use. Any chance to get them compatible?

**Comment by ironmonk88** [comment]
Show Drag Distance has kind of been replaced by Drag Ruler.
At least I'd recommend using Terrain Ruler and Drag Ruler with Enhanced Terrain Layer.

I know the code that isn't compatible with Show Drag Distance... and unfortunately I'm pretty sure there's not a convenient way to make them talk any more.  At least not without affecting the performance of other modules.  And it's probably not worth it when there are alternatives.

**Comment by Verthiss** [comment]
Oh, I didn't know about Drag Ruler or Terrain Ruler, thanks for the tip! :)
And since it looks like Terrain Ruler was made specifically to work with Enhanced Terrrain Layer, I would maybe suggest writing a sentence about those modules in this module's description so more people know? ;)

**Comment by ironmonk88** [comment]
Updated the Readme to let people know the recommended Ruler modules.
