### ISSUE TITLE
used by other modules to calculate difficult terrain

### ISSUE THREAD

**Issue by CaosFR** [ironmonk108/enhanced-terrain-layer#64]
Hi,

I love your mod but I'm a little tired to calculte de mouvement of my players. I'm very interessting to know wich other modules do you recommand for calculate difficult terrain.
 Thanks

**Comment by ironmonk88** [comment]
I'd recommend both Drag Ruler and Terrain Ruler.  They work well with Enhanced Terrain Layer.

**Comment by CaosFR** [comment]
Thanks for your reply.
