### ISSUE TITLE
Mvoing terrain cannot be undone using Ctrl+Z

### ISSUE THREAD

**Issue by manuelVo** [ironmonk108/enhanced-terrain-layer#69]
Moving terrain cannot be undone using Ctrl+Z. This can lead to unexpected behavior:

**Steps to reproduce**
1. Create a terrain
2. Move it
3. Press Ctrl+Z
Enhanced Terrain Layer will now undo the terrain creation (thus removing it) instead of moving it back to the original spot.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
