### ISSUE TITLE
Token Control Measure Distance Counts Tokens as Difficult Terrain

### ISSUE THREAD

**Issue by AsianDumpring** [ironmonk108/enhanced-terrain-layer#73]
The token control ruler tool counts tokens as difficult terrain, even when no tokens are selected. Is this desired behavior? Testing whether someone can cast spells or helping to envision theater of the mind is bunked because players can't use the ruler tool, but I want to be able to count corpses as difficult terrain when players are moving. 

IS: Ruler is counting tokens as difficult terrain, even when no tokens are selected and the ruler is being used to assist theater of the mind 

SB: Ruler tool should not count tokens as difficult terrain. Tokens are only contain a difficult terrain component for the purposes of green/yellow/red movement shading when dragging tokens, not when determining spell distance or evaluating distance for theater of the mind.

**Comment by ironmonk88** [comment]
That is an issue with the Ruler, not with Enhanced Terrain Layer.
Enhanced Terrain Layer is just a library, it's up to the ruler to determine how it displays that information.

**Comment by ironmonk88** [comment]
Closing this issue, cleaning up tickets.
