### ISSUE TITLE
'water' is not recognized using reduce: [{id:'water',value:1}] in the options for the getCost function.

### ISSUE THREAD

**Issue by PepijnMC** [ironmonk108/enhanced-terrain-layer#74]
As the title suggest, trying to set the cost of water terrain to 1 does not seem to work while using other ids like desert and arctic work as expected.
![Screenshot_1](https://user-images.githubusercontent.com/13134303/149664445-a9e1f609-b5a6-4569-9b36-d1819b671292.png)

**Comment by ironmonk88** [comment]
When I try reducing water it's working correctly.  And there's nothing strange about the water environment.  Checked on the code and there's no strange spelling mistakes.

**Comment by PepijnMC** [comment]
Although I was able to reproduce this before (or at least I thought so), I no longer can. I'll assume I made a mistake and close this.
