### ISSUE TITLE
New terrain ignores toolbar cost setting

### ISSUE THREAD

**Issue by epsilon7430** [ironmonk108/enhanced-terrain-layer#76]
Just installed module version 1.0.37 on FVTT 9.245 and found with cost to the right of drawing tool set to e.g., 2, a newly drawn terrain area defaults to 1 cost and requires cost to be changed manually afterwards.  Draw tool seems to be ignoring the cost setting in the toolbar.

**Comment by epsilon7430** [comment]
I suspect release 1.0.36 was meant to fix #76.  After upgrading, the terrain toolbar cost in the toolbar matches the scene default (1), however, the inc/dec buttons are blank and don't function.
![image](https://user-images.githubusercontent.com/96020742/151749047-92819f05-d7f3-47eb-8563-2bc25f470f86.png)

**Comment by ironmonk88** [comment]
Have you checked the scene settings?  If it's set there, then it will disable the default controls.

**Comment by epsilon7430** [comment]
Confirming that 1.0.39 has restored the missing up/down cost arrows.  I checked the scene and deleted the default value of 1 and the up/down settings were enabled afterwards.  I didn't fully realize that a recent release must have changed the behaviour because only a couple of weeks ago I had added terrain to a different scene without having to change scene related settings - at the time, all terrain was created with cost 2.

It would be helpful if the scene default cost was set to 2 instead of 1.  Unless I'm mistaken, the most common use case is to add cost 2 terrain.

Thanks for this module and its improvements!

**Comment by apoapostolov** [comment]
Hello, I am having the same issue. I cannot change the value from 1 to any other value. 

![image](https://user-images.githubusercontent.com/4083812/153477246-dc0e13cc-acc9-448e-85a0-73651f5f182b.png)

**Comment by apoapostolov** [comment]
Is there solution to the problem? The mod is impossible to use in its current state?

**Comment by ironmonk88** [comment]
Have you checked the scene settings? If it's set there, then it will disable the default controls.

**Comment by ironmonk88** [comment]
Closing this issue as it's more of a miscommunication than an issue.
Added stylings in the latest version to make it a little clearer that the Scene has taken over default values.
