### ISSUE TITLE
Extra buttons break sidebar

### ISSUE THREAD

**Issue by revilowaldow** [ironmonk108/enhanced-terrain-layer#79]
# You've got some floaty buttons going wandering across the map.
![image](https://user-images.githubusercontent.com/52298102/156856036-591bb3e3-05c5-4f35-972e-28f76d142759.png)

## I suspect, though cannot reproduce or prove that they also briefly caused this:
![image](https://user-images.githubusercontent.com/52298102/156856113-bfc95159-0a61-4df7-9e20-554317867212.png)

**Comment by ironmonk88** [comment]
I'm assuming this has been fixed.
Either I updated the code and forgot about it and just havn't released it yet, or it was an issue with Foundry and they fixed it.

**Comment by ironmonk88** [comment]
Closing the ticket, but please re-open if this is still an issue with the latest version.
