### ISSUE TITLE
Allow measured templates to also work for Features

### ISSUE THREAD

**Issue by RogueEntityX** [ironmonk108/enhanced-terrain-layer#80]
``The Terrain Layer will also let you assign difficulty to a measured templates. You can use this for spells that set difficult terrain.``

Unless I've missed something, or set it up wrong. it seems that measured templates that assign difficulty only work for spells--the terrain options do not appear on Features. Is it possible to include this on Features as well as Spells?

**Comment by ironmonk88** [comment]
So I updated it to check and see if the "item" has an area effect.  And if it does, it will add the terrain controls.
That should be more accurate as any spell that doesn't have an area effect won't need the terrain controls.  And anything else that does have an area effect can now use it.
So if the feat has area effect, the terrain controls will show up.

**Comment by ironmonk88** [comment]
Should be updated with the latest version.
