### ISSUE TITLE
Suggestion: Add circle template to create difficult terrain

### ISSUE THREAD

**Issue by ckdragons** [ironmonk108/enhanced-terrain-layer#85]
Some effects in a game allow a radius to be set as difficult terrain (i.e. grasping tentacles). It would be great if there was a circle template that can be used to create this area, similar to the Circle Template under Measurement Controls.

**Comment by ironmonk88** [comment]
You could just use the Circle Template.
![image](https://user-images.githubusercontent.com/75920956/166128661-9c57b3b6-508d-46c6-b911-468fbaee5667.png)

**Comment by ckdragons** [comment]
Got it, thank you
