### ISSUE TITLE
Terrain Effects on Spells on PC characters aren't working

### ISSUE THREAD

**Issue by ckdragons** [ironmonk108/enhanced-terrain-layer#87]
1. Terrain Effects fields are invisible.
2. Terrain Effects are not transferring to the Measured Spell Template that is created by the spell settings.
![image](https://user-images.githubusercontent.com/84493092/166158975-c2f9b5eb-1392-41b3-b323-6deff6769d29.png)

**Comment by ironmonk88** [comment]
What system are you using? Can you check with no other modules but Enhanced Terrain?
Are there any errors in the console?
It's working on my end, so I suspect there's some interference happening.

**Comment by ckdragons** [comment]
Using PF1E. Disabled all modules except Enhanced Terrain. Loaded newest version that was available earlier today.
![image](https://user-images.githubusercontent.com/84493092/167276024-c641d472-1cbd-4717-98fb-d7a058a025bd.png)
![image](https://user-images.githubusercontent.com/84493092/167276042-e69f0982-4f04-4abb-863c-40561b91f856.png)
![image](https://user-images.githubusercontent.com/84493092/167276050-dd707042-18ce-4809-bfbf-ad7a5db70816.png)
![image](https://user-images.githubusercontent.com/84493092/167276058-85635a2a-46e4-4093-98be-ba428c056ec4.png)
![image](https://user-images.githubusercontent.com/84493092/167276062-fd53ad72-3078-4cd8-981a-d51f5d47d14b.png)
Let me know if you need anything else.

**Comment by ckdragons** [comment]
The normal template coloring is working.
![image](https://user-images.githubusercontent.com/84493092/167276076-013f09a6-cd3d-495e-b115-35db86d864c6.png)
![image](https://user-images.githubusercontent.com/84493092/167276082-1e635cdd-063b-4b44-8abe-b79c1c70da17.png)

**Comment by ironmonk88** [comment]
Ohhhhh... terrain colours don't get transferred over.
I'll add that as a feature request.

**Comment by ckdragons** [comment]
Sorry for the confusion. I thought that was what was intended since the options were readily available on measured templates.  :)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
