### ISSUE TITLE
Terain color opacity

### ISSUE THREAD

**Issue by KitCat420** [ironmonk108/enhanced-terrain-layer#88]
It would be awesome to have the option to adjust the opacity of individual terrains. I personally find they obscure the map too much at 100% opacity and would prefer a more subtle overlay, especially for terrains that may not have a directly dangerous/negative effect for the character

**Comment by ironmonk88** [comment]
You can change the opacity at the scene level, but I'll add them to the individual terrains.
Kinda surprised that I hadn't added it already.

**Comment by KitCat420** [comment]
Ah, I had missed that option, that's a good workaround until I can control them per terrain. Will we also be able to configure default opacity values for our terrain overwrites?

**Comment by ironmonk88** [comment]
What system are you using? Can you check with no other modules but Enhanced Terrain?
It's working on my end, so I suspect there's some interference happening.

**Comment by ironmonk88** [comment]
Should be added to the latest version.
