### ISSUE TITLE
[Feature Request] Separate toggles for treating hostile/non-hostile tokens as difficult terrain

### ISSUE THREAD

**Issue by esheyw** [ironmonk108/enhanced-terrain-layer#92]
PF2e rules let you move through willing creatures' spaces freely, and enemy spaces as difficult terrain if you pass a check. Obviously there's a lot of edge cases there, but a simple distinction between hostile tokens and non-hostile would be enough, if possible.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
