### ISSUE TITLE
Freedom of Movement Toggle

### ISSUE THREAD

**Issue by kiligir** [ironmonk108/enhanced-terrain-layer#94]
My particular party likes to cast Freedom of Movement (which among other things ignores difficult terrain, to save anyone the trouble of looking up the spell). To make this system agnostic, would it be possible to add a toggle hotkey that ignores difficult terrain when held?

**Comment by ironmonk88** [comment]
This would be up to the Ruler to do that since it's the ruler that's calculating the cost of difficult terrain.
And if you're using Drag Ruler/Terrain Ruler, it already has that button.
![image](https://user-images.githubusercontent.com/75920956/194661650-2f8de574-b8d0-4d61-9535-69da95ce9d84.png)
