### ISSUE TITLE
adding fixed values instead of multiplier 

### ISSUE THREAD

**Issue by patrickmohrmann** [ironmonk108/enhanced-terrain-layer#95]
For the Earthdawn Ruleset difficult terrain reduces the movement by a fixed value. It would be nice if the "cost" field would represent the one-time additional movemnt cost.

**Comment by Armandeus66** [comment]
[PF2E](https://2e.aonprd.com/Rules.aspx?ID=453) charges an additional 5 feet of movement, and doesn't use a multiplier as well.

**Comment by ironmonk88** [comment]
This is up to a Ruler to implement.  Enhanced Terrain Layer is essentially just a library, it's up to the Ruler to specify what to do with the cost.  So ETL can return any number you want, but the Ruler applies it to the cost of movement.
