### ISSUE TITLE
measurements issues with Foundry VTT Mount Up or Token Attacher

### ISSUE THREAD

**Issue by KammaKhazi** [ironmonk108/enhanced-terrain-layer#96]
I absolutely love the terrain layer combined with the terrain ruler thank you. But it causes incorrect measurement issues when trying to implement mounted combat (I'm using the mod Foundry VTT mount up, but testing using Token Attacher is the same issue). Going one direction it correctly measures the distance, going in the opposite direction it messes it up and adds 5 feet. Image attached.
![TokenAttacherConflicts](https://user-images.githubusercontent.com/81476445/177819924-bafb8116-061d-4d8f-8fd5-1064a69baf10.png)

**Comment by ironmonk88** [comment]
I believe this is fixed with the latest version.  If it is not, please re-open this ticket.

**Comment by KammaKhazi** [comment]
awesome thank you

On 11 Nov 2022, at 22:49, ironmonk88 ***@***.***> wrote:

﻿

I believe this is fixed with the latest version. If it is not, please re-open this ticket.
