### ISSUE TITLE
Error when using `canvas.terrain.terrainFromPixels`

### ISSUE THREAD

**Issue by caewok** [ironmonk108/enhanced-terrain-layer#98]
Foundry v10.284; Enhanced Terrain Layer 1.0.43

Create a terrain and then try to use `canvas.terrain.terrainFromPixels` in the console. I get this error:

> terrainlayer.js:320 Uncaught TypeError: t.shape.contains is not a function
>     at terrainlayer.js:320:28
>     at Array.filter (<anonymous>)
>     at TerrainLayer.terrainFromPixels (terrainlayer.js:317:40)
>     at <anonymous>:1:27

It looks like in `terrainFromPixels`, the `shape.contains` method no longer exists: `t.shape.contains(testX, testY);`.

**Comment by manuelVo** [comment]
I second this. A similar error (with the same cause) pops up when calling the `cost` function while any terrain is placed on the canvas.

**Comment by manuelVo** [comment]
This should be fixed in ETL v10.3

**Comment by caewok** [comment]
The error is fixed, but I think there is still something wrong with that function. 

Here is a basic example, with one terrain and a token inside the terrain:
<img width="363" alt="Screen Shot 2022-09-29 at 1 41 19 PM" src="https://user-images.githubusercontent.com/1267134/193139160-4cd5af8c-f06e-4dbd-b41f-4941838d6079.png">

`canvas.terrain.terrainFromPixels` cannot find the terrain for that token location. Digging down, the problem seems to be that the function is using `shape._pixishape` which differs from the `bounds`. 

```js
{x: _token.x, y: _token.y}
// {x: 1900, y: 2100}
canvas.terrain.terrainFromPixels(_token.x, _token.y)
// []
[t] = canvas.terrain.placeables
// [Terrain]
t.bounds
// e {x: 1637.5, y: 1850, width: 705, height: 657, type: 1}
t.bounds.contains(_token.x, _token.y)
// true
t.shape._pixishape
// e {x: 1990, y: 2178.5, width: 705, height: 657, type: 1}
t.shape.containsPoint(_token.x, _token.y)
// false
```

**Comment by ironmonk88** [comment]
I believe this is fixed with the latest version.  If it is not, please re-open this ticket.
