### ISSUE TITLE
Bug: Terrain Effects are mixing with MIDI

### ISSUE THREAD

**Issue by Crowguard** [ironmonk108/enhanced-terrain-layer#99]
The terrain fields on spells & items are being mixed in with MIDI fields.

### Normal
![image](https://user-images.githubusercontent.com/99844555/189453873-f573cb1e-304d-4951-8134-ab19f57feab0.png)
### MIDI Active
![image](https://user-images.githubusercontent.com/99844555/189454070-54099b27-7dc0-48a5-8c29-aab659a7af72.png)

![image](https://user-images.githubusercontent.com/99844555/189454142-e25b56fe-6d31-4da3-ad24-5c60fafd6bc8.png)

ETL 1.0.42
MIDI 0.9.78

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
